#!/usr/bin/env python3
import os

BASE = "D:/Games/dice-rpg-game-2026-new"

def edit_file(rel_path, old_str, new_str):
    path = os.path.join(BASE, rel_path).replace("\\", "/")
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        if old_str in content:
            new_content = content.replace(old_str, new_str, 1)
            with open(path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"OK: {rel_path}")
        else:
            print(f"MISS: {old_str[:70]!r} in {rel_path}")
    except Exception as e:
        print(f"ERR {rel_path}: {e}")

# ========================
# ACTIONS
# ========================
action_edits = [
    # region_1 items
    ("resources/actions/items/region_1/ember_staff_flame_burst_action.tres",
     'action_description = "Applies 3 Burn. Echoes at 40% if dice total is 10 or more."',
     'action_description = "Applies 3 [status:burn]. Echoes at 40% if dice total is 10 or more."'),
    ("resources/actions/items/region_1/frost_staff_frost_bolt_action.tres",
     'action_description = "Applies 5 Chill."',
     'action_description = "Applies 5 [status:chill]."'),
    ("resources/actions/items/region_1/frost_wand_ice_shard_action.tres",
     'action_description = "Applies 2 Chill. Restores 1 mana on use."',
     'action_description = "Applies 2 [status:chill]. Restores 1 mana on use."'),
    ("resources/actions/items/region_1/iron_mace_bludgeon_action.tres",
     'action_description = "Applies Stun."',
     'action_description = "Applies [status:stunned|Stun]."'),
    ("resources/actions/items/region_1/iron_warhammer_pulverize_action.tres",
     'action_description = "Applies 3 Corrode. "',
     'action_description = "Applies 3 [status:corrode]. "'),
    ("resources/actions/items/region_1/marine_halberd_formation_thrust_action.tres",
     'action_description = "Applies 2 Expose."',
     'action_description = "Applies 2 [status:expose]."'),
    ("resources/actions/items/region_1/officers_rapier_lunge_action.tres",
     'action_description = "Applies 2 marks. Follow-up hits consume marks for bonus damage."',
     'action_description = "Applies 2 [status:marked|marks]. Follow-up hits consume marks for bonus damage."'),
    ("resources/actions/items/region_1/sanctum_stiletto_puncture_action.tres",
     'action_description = "A quick pierce that applies 2 Bleed. Reliable opener for bleed builds."',
     'action_description = "A quick pierce that applies 2 [status:bleed]. Reliable opener for bleed builds."'),
    ("resources/actions/items/region_1/spark_wand_zap_action.tres",
     'action_description = "A quick shock that applies 2 Static. Restores 1 mana on use."',
     'action_description = "A quick shock that applies 2 [status:static]. Restores 1 mana on use."'),
    ("resources/actions/items/region_1/storm_staff_thunderstrike_action.tres",
     'action_description = "Applies 3 Static. Chains to a second target for half damage."',
     'action_description = "Applies 3 [status:static]. Chains to a second target for half damage."'),
    ("resources/actions/items/region_1/venom_staff_venom_lance_action.tres",
     'action_description = "Applies 4 Poison."',
     'action_description = "Applies 4 [status:poison]."'),
    ("resources/actions/items/region_1/cinder_wand_ember_shot_action.tres",
     'action_description = "Applies 1 Burn. Restores 1 mana."',
     'action_description = "Applies 1 [status:burn]. Restores 1 mana."'),
    # mage flame actions
    ("resources/actions/mage/flame/detonate_action.tres",
     'action_description = "Consume all Burn on target. Deal fire x1.2 + 3 per consumed Burn stack."',
     'action_description = "Consume all [status:burn] on target. Deal [element:fire] x1.2 + 3 per consumed [status:burn] stack."'),
    ("resources/actions/mage/flame/conflagration_action.tres",
     'action_description = "Fire x0.8 to ALL enemies. Apply 3 Burn to all. Burn explosions from this deal double damage."',
     'action_description = "[element:fire] x0.8 to ALL enemies. Apply 3 [status:burn] to all. [status:burn] explosions from this deal double damage."'),
    ("resources/actions/mage/flame/sear_action.tres",
     'action_description = "Deal fire damage equal to die value. Apply Burn stacks equal to die value."',
     'action_description = "Deal [element:fire] damage equal to die value. Apply [status:burn] stacks equal to die value."'),
    # mage storm actions
    ("resources/actions/mage/storm/thunderclap_action.tres",
     'action_description = "Deal shock damage equal to die value. Apply Static stacks equal to die value."',
     'action_description = "Deal [element:shock] damage equal to die value. Apply [status:static] stacks equal to die value."'),
    ("resources/actions/mage/storm/storm_surge_action.tres",
     'action_description = "Deal x0.8 shock damage to ALL enemies. Apply 3 Static to all. Chain returns to primary for an extra hit."',
     'action_description = "Deal x0.8 [element:shock] damage to ALL enemies. Apply 3 [status:static] to all. Chain returns to primary for an extra hit."'),
    ("resources/actions/mage/storm/conjure_storm_sprite_action.tres",
     'action_description = "Summon a Storm Sprite that zaps a random enemy each turn for 4 shock damage and 1 Static. HP scales with die value."',
     'action_description = "Summon a Storm Sprite that zaps a random enemy each turn for 4 [element:shock] damage and 1 [status:static]. HP scales with die value."'),
    ("resources/actions/mage/storm/lightning_bolt_action.tres",
     'action_description = "Deal x1.2 shock damage. +3 bonus damage per Static stack on target. Chain to 1 enemy for 50%."',
     'action_description = "Deal x1.2 [element:shock] damage. +3 bonus damage per [status:static] stack on target. Chain to 1 enemy for 50%."'),
    # mage frost actions
    ("resources/actions/mage/frost/shatter_action.tres",
     'action_description = "Deal x1.5 ice damage. If Frozen: x4.5 instead and consume Freeze."',
     'action_description = "Deal x1.5 [element:ice] damage. If [status:freeze|Frozen]: x4.5 instead and consume [status:freeze]."'),
    ("resources/actions/mage/frost/frost_spike_action.tres",
     'action_description = "Deal ice damage equal to die value. Apply Chill stacks equal to die value."',
     'action_description = "Deal [element:ice] damage equal to die value. Apply [status:chill] stacks equal to die value."'),
    ("resources/actions/mage/frost/absolute_zero_action.tres",
     'action_description = "Deal ice damage to ALL enemies equal to dice total. Apply Chill = dice total to all. If any Freeze triggers, reset Shatter charge."',
     'action_description = "Deal [element:ice] damage to ALL enemies equal to dice total. Apply [status:chill] = dice total to all. If any [status:freeze] triggers, reset Shatter charge."'),
    # enemy_base
    ("resources/actions/enemy_base/smash.tres",
     'action_description = "Deals 1D+2 Blunt damage."',
     'action_description = "Deals 1D+2 [element:blunt] damage."'),
    ("resources/actions/enemy_base/brace.tres",
     'action_description = "Gain 2 Fortified for 1 turn."',
     'action_description = "Gain 2 [status:fortified] for 1 turn."'),
    ("resources/actions/enemy_base/crushing_blow.tres",
     'action_description = "Heavy Blunt hit. Applies Corrode."',
     'action_description = "Heavy [element:blunt] hit. Applies [status:corrode]."'),
    ("resources/actions/enemy_base/magic_bolt.tres",
     'action_description = "Deals 1D+2 Fire damage at 1.1\u00d7."',
     'action_description = "Deals 1D+2 [element:fire] damage at 1.1\u00d7."'),
    ("resources/actions/enemy_base/ward.tres",
     'action_description = "Gain 3 Warded."',
     'action_description = "Gain 3 [status:warded]."'),
    ("resources/actions/enemy_base/ignite.tres",
     'action_description = "Fire hit. Applies 2 Burn."',
     'action_description = "[element:fire] hit. Applies 2 [status:burn]."'),
    ("resources/actions/enemy_base/slam.tres",
     'action_description = "Deals 1D+1 Blunt damage at 0.7\u00d7."',
     'action_description = "Deals 1D+1 [element:blunt] damage at 0.7\u00d7."'),
    ("resources/actions/enemy_base/shield_wall.tres",
     'action_description = "Gain 3 Fortified for 1 turn."',
     'action_description = "Gain 3 [status:fortified] for 1 turn."'),
    ("resources/actions/enemy_base/fortify.tres",
     'action_description = "Gain 4 Fortified + 2 Braced for 1 turn."',
     'action_description = "Gain 4 [status:fortified] + 2 [status:braced] for 1 turn."'),
    ("resources/actions/enemy_base/precision_strike.tres",
     'action_description = "Deals 1D+3 Piercing damage."',
     'action_description = "Deals 1D+3 [element:piercing] damage."'),
    ("resources/actions/enemy_base/sidestep.tres",
     'action_description = "Gain 2 Braced for 1 turn."',
     'action_description = "Gain 2 [status:braced] for 1 turn."'),
    ("resources/actions/enemy_base/crippling_thrust.tres",
     'action_description = "Piercing hit. Applies 2 Bleed."',
     'action_description = "[element:piercing] hit. Applies 2 [status:bleed]."'),
    ("resources/actions/enemy_base/stab.tres",
     'action_description = "Deals 1D Piercing damage."',
     'action_description = "Deals 1D [element:piercing] damage."'),
    ("resources/actions/enemy_base/quick_slash.tres",
     'action_description = "Deals 1D+1 Slashing damage at 0.8\u00d7."',
     'action_description = "Deals 1D+1 [element:slashing] damage at 0.8\u00d7."'),
    ("resources/actions/enemy_base/fan_of_blades.tres",
     'action_description = "2 random strikes. Applies 1 Bleed."',
     'action_description = "2 random strikes. Applies 1 [status:bleed]."'),
    ("resources/actions/enemy_base/war_cry.tres",
     'action_description = "Empower an ally \u2014 increased damage."',
     'action_description = "[status:empowered|Empower] an ally \u2014 increased damage."'),
    ("resources/actions/enemy_base/rally.tres",
     'action_description = "Empower all allies + 2 Fortified to all."',
     'action_description = "[status:empowered|Empower] all allies + 2 [status:fortified] to all."'),
    ("resources/actions/enemy_base/hex.tres",
     'action_description = "Apply 1 Slowed to player."',
     'action_description = "Apply 1 [status:slowed] to player."'),
    ("resources/actions/enemy_base/arcane_push.tres",
     'action_description = "Deals 1D+1 Shadow damage at 0.7\u00d7."',
     'action_description = "Deals 1D+1 [element:shadow] damage at 0.7\u00d7."'),
    ("resources/actions/enemy_base/barrier_pulse.tres",
     'action_description = "Gain 2 stacks of Warded."',
     'action_description = "Gain 2 stacks of [status:warded]."'),
    ("resources/actions/enemy_base/poke.tres",
     'action_description = "Weak Piercing hit at 0.5\u00d7."',
     'action_description = "Weak [element:piercing] hit at 0.5\u00d7."'),
    ("resources/actions/enemy_base/hamstring.tres",
     'action_description = "Apply 2 Slowed to player."',
     'action_description = "Apply 2 [status:slowed] to player."'),
    ("resources/actions/enemy_base/sabotage.tres",
     'action_description = "Apply 2 Slowed + 2 Corrode."',
     'action_description = "Apply 2 [status:slowed] + 2 [status:corrode]."'),
    ("resources/actions/enemy_base/spark.tres",
     'action_description = "Deals 1D Shock damage."',
     'action_description = "Deals 1D [element:shock] damage."'),
    ("resources/actions/enemy_base/frost_shard.tres",
     'action_description = "Deals 1D+1 Ice damage at 0.8\u00d7."',
     'action_description = "Deals 1D+1 [element:ice] damage at 0.8\u00d7."'),
    ("resources/actions/enemy_base/chain_spark.tres",
     'action_description = "Chain Shock to 2 targets. Applies 1 Chill."',
     'action_description = "Chain [element:shock] to 2 targets. Applies 1 [status:chill]."'),
    ("resources/actions/flaming_fingies_action_debug.tres",
     'action_description = "Applies a Burn stack with spicy touching."',
     'action_description = "Applies a [status:burn] stack with spicy touching."'),
    ("resources/actions/enemy/goblins/goblin_stab.tres",
     'action_description = "Deals 1D Piercing damage."',
     'action_description = "Deals 1D [element:piercing] damage."'),
    ("resources/actions/flame_strike.tres",
     'action_description = "A slash for 2D+10 [color=red]Fire[/color] damage."',
     'action_description = "A slash for 2D+10 [element:fire] damage."'),
]

for rel, old, new in action_edits:
    edit_file(rel, old, new)

print("All actions done")
