#!/usr/bin/env python3
import os
import re
import glob

BASE = "D:/Games/dice-rpg-game-2026-new"

# Specific description edits for affixes and dice_affixes
# Format: (relative_path, old_desc_value, new_desc_value)
# Only the value inside the quotes

affix_edits = [
    # ==== CLASS AFFIXES - FLAME ====
    ("resources/affixes/classes/mage/flame/accelerant/accelerant_r1_affix.tres",
     "All Burn application gains +1 bonus stack.",
     "All [status:burn] application gains +1 bonus stack."),
    ("resources/affixes/classes/mage/flame/accelerant/accelerant_r2_affix.tres",
     "All Burn application gains +2 bonus stacks.",
     "All [status:burn] application gains +2 bonus stacks."),
    ("resources/affixes/classes/mage/flame/immolate/immolate_r1_affix.tres",
     "15% chance: dealing fire damage applies 1 Burn.",
     "15% chance: dealing [element:fire] damage applies 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/immolate/immolate_r2_affix.tres",
     "30% chance: dealing fire damage applies 1 Burn.",
     "30% chance: dealing [element:fire] damage applies 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/immolate/immolate_r3_affix.tres",
     "45% chance: dealing fire damage applies 1 Burn.",
     "45% chance: dealing [element:fire] damage applies 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/fuel_the_fire/fuel_the_fire_r1_affix.tres",
     "Fire die deals +2 bonus damage vs burning targets.",
     "[element:fire] die deals +2 bonus damage vs [status:burn|burning] targets."),
    ("resources/affixes/classes/mage/flame/fuel_the_fire/fuel_the_fire_r2_affix.tres",
     "Fire die deals +4 bonus damage vs burning targets.",
     "[element:fire] die deals +4 bonus damage vs [status:burn|burning] targets."),
    ("resources/affixes/classes/mage/flame/fuel_the_fire/fuel_the_fire_r3_affix.tres",
     "Fire die deals +6 bonus damage vs burning targets.",
     "[element:fire] die deals +6 bonus damage vs [status:burn|burning] targets."),
    ("resources/affixes/classes/mage/flame/flashpoint/flashpoint_r1_affix.tres",
     "Burn explosion splashes 40% of explosion damage to all others.",
     "[status:burn] explosion splashes 40% of explosion damage to all others."),
    ("resources/affixes/classes/mage/flame/flashpoint/flashpoint_r2_affix.tres",
     "Burn explosion splashes 60% of explosion damage to all others.",
     "[status:burn] explosion splashes 60% of explosion damage to all others."),
    ("resources/affixes/classes/mage/flame/firestorm/firestorm_r1_affix.tres",
     "Fire die chains to 1 enemy for 25% damage, applying 1 Burn.",
     "[element:fire] die chains to 1 enemy for 25% damage, applying 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/firestorm/firestorm_r2_affix.tres",
     "Fire die chains to 1 enemy for 40% damage, applying 1 Burn.",
     "[element:fire] die chains to 1 enemy for 40% damage, applying 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/forge_bond/forge_bond_burn_first_affix.tres",
     "Fire die in FIRST position: apply 1 Burn.",
     "[element:fire] die in FIRST position: apply 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/forge_bond/forge_bond_burn_last_affix.tres",
     "Fire die in LAST position: apply 1 Burn.",
     "[element:fire] die in LAST position: apply 1 [status:burn]."),
    ("resources/affixes/classes/mage/flame/pyroclastic_flow/pyroclastic_flow_r1_affix.tres",
     "When Burn explosion triggers: apply 2 Burn to ALL other enemies.",
     "When [status:burn] explosion triggers: apply 2 [status:burn] to ALL other enemies."),
    ("resources/affixes/classes/mage/flame/conflagration/conflagration_explode_affix.tres",
     "Burn explosions during Conflagration deal 2x damage.",
     "[status:burn] explosions during Conflagration deal 2x damage."),
    ("resources/affixes/classes/mage/flame/ignite/ignite_ca_affix.tres",
     "Chromatic Bolt applies 1 Burn on hit (requires fire die).",
     "Chromatic Bolt applies 1 [status:burn] on hit (requires [element:fire] die)."),
    ("resources/affixes/classes/mage/flame/ignite/ignite_element_unlock.tres",
     "Unlocks Fire mana element.",
     "Unlocks [element:fire] mana element."),
    ("resources/affixes/classes/mage/flame/flashfire/flashfire_r1_affix.tres",
     "Fire die on max roll: apply 2 Burn to random other enemy.",
     "[element:fire] die on max roll: apply 2 [status:burn] to random other enemy."),
    ("resources/affixes/classes/mage/flame/flashfire/flashfire_r2_affix.tres",
     "Fire die on max roll: apply 3 Burn to random other enemy.",
     "[element:fire] die on max roll: apply 3 [status:burn] to random other enemy."),
    ("resources/affixes/classes/mage/flame/pyre/pyre_r1_affix.tres",
     "Burn tick damage deals +1 bonus fire damage per stack.",
     "[status:burn] tick damage deals +1 bonus [element:fire] damage per stack."),
    ("resources/affixes/classes/mage/flame/pyre/pyre_r2_affix.tres",
     "Burn tick damage deals +2 bonus fire damage per stack.",
     "[status:burn] tick damage deals +2 bonus [element:fire] damage per stack."),
    ("resources/affixes/classes/mage/flame/inferno_cascade/inferno_cascade_threshold_affix.tres",
     "Burn explosion threshold reduced to 4.",
     "[status:burn] explosion threshold reduced to 4."),
    ("resources/affixes/classes/mage/flame/inferno_cascade/inferno_cascade_double_affix.tres",
     "Burn explosions deal 2x damage.",
     "[status:burn] explosions deal 2x damage."),
    ("resources/affixes/classes/mage/flame/inferno_cascade/inferno_cascade_first_affix.tres",
     "FIRST fire die applies 1 Burn to all enemies.",
     "FIRST [element:fire] die applies 1 [status:burn] to all enemies."),

    # ==== CLASS AFFIXES - STORM ====
    ("resources/affixes/classes/mage/storm/ionize/ionize_r1_affix.tres",
     "Pulling shock die applies 1 Static to random enemy.",
     "Pulling [element:shock] die applies 1 [status:static] to random enemy."),
    ("resources/affixes/classes/mage/storm/ionize/ionize_r2_affix.tres",
     "Pulling shock die applies 2 Static to random enemy.",
     "Pulling [element:shock] die applies 2 [status:static] to random enemy."),
    ("resources/affixes/classes/mage/storm/ionize/ionize_r3_affix.tres",
     "Pulling shock die applies 3 Static to random enemy.",
     "Pulling [element:shock] die applies 3 [status:static] to random enemy."),
    ("resources/affixes/classes/mage/storm/live_wire/live_wire_r1_affix.tres",
     "Shock dice apply +1 bonus Static if target already has Static.",
     "[element:shock] dice apply +1 bonus [status:static] if target already has [status:static]."),
    ("resources/affixes/classes/mage/storm/live_wire/live_wire_r2_affix.tres",
     "Shock dice apply +2 bonus Static if target already has Static.",
     "[element:shock] dice apply +2 bonus [status:static] if target already has [status:static]."),
    ("resources/affixes/classes/mage/storm/voltaic_surge/voltaic_surge_r1_affix.tres",
     "Shock dice deal +1 bonus damage per Static stack on target.",
     "[element:shock] dice deal +1 bonus damage per [status:static] stack on target."),
    ("resources/affixes/classes/mage/storm/voltaic_surge/voltaic_surge_r2_affix.tres",
     "Shock dice deal +2 bonus damage per Static stack on target.",
     "[element:shock] dice deal +2 bonus damage per [status:static] stack on target."),
    ("resources/affixes/classes/mage/storm/voltaic_surge/voltaic_surge_r3_affix.tres",
     "Shock dice deal +3 bonus damage per Static stack on target.",
     "[element:shock] dice deal +3 bonus damage per [status:static] stack on target."),
    ("resources/affixes/classes/mage/storm/storm_charge/storm_charge_r1_affix.tres",
     "Applying Static to target with 8+ stacks: splash 1 Static to all others.",
     "Applying [status:static] to target with 8+ stacks: splash 1 [status:static] to all others."),
    ("resources/affixes/classes/mage/storm/storm_charge/storm_charge_r2_affix.tres",
     "Applying Static to target with 8+ stacks: splash 2 Static to all others.",
     "Applying [status:static] to target with 8+ stacks: splash 2 [status:static] to all others."),
    ("resources/affixes/classes/mage/storm/storm_charge/storm_charge_r3_affix.tres",
     "Applying Static to 10+ target spreads 3 to others.",
     "Applying [status:static] to 10+ target spreads 3 to others."),
    ("resources/affixes/classes/mage/storm/arc_conduit/arc_conduit_r1_affix.tres",
     "Shock dice chain to +1 extra target. Bounces apply 1 Static.",
     "[element:shock] dice chain to +1 extra target. Bounces apply 1 [status:static]."),
    ("resources/affixes/classes/mage/storm/arc_conduit/arc_conduit_r2_affix.tres",
     "Shock dice chain to +1 extra target. Bounces apply 2 Static.",
     "[element:shock] dice chain to +1 extra target. Bounces apply 2 [status:static]."),
    ("resources/affixes/classes/mage/storm/static_discharge/static_discharge_r1_affix.tres",
     "When target with Static dies: deal remaining stacks as shock AoE, apply half as Static to all.",
     "When target with [status:static] dies: deal remaining stacks as [element:shock] AoE, apply half as [status:static] to all."),
    ("resources/affixes/classes/mage/storm/thunderhead/thunderhead_r1_affix.tres",
     "Turn start: apply 2 Static to all enemies.",
     "Turn start: apply 2 [status:static] to all enemies."),
    ("resources/affixes/classes/mage/storm/thunderhead/thunderhead_r2_affix.tres",
     "Turn start: apply 3 Static to all enemies.",
     "Turn start: apply 3 [status:static] to all enemies."),
    ("resources/affixes/classes/mage/storm/eye_of_the_storm/eye_max_stacks_affix.tres",
     "Static max stacks doubled (20 -> 40).",
     "[status:static] max stacks doubled (20 -> 40)."),
    ("resources/affixes/classes/mage/storm/eye_of_the_storm/eye_first_strike_affix.tres",
     "Shock die in FIRST position applies 2 Static to all enemies on use.",
     "[element:shock] die in FIRST position applies 2 [status:static] to all enemies on use."),
    ("resources/affixes/classes/mage/storm/galvanic_pulse/galvanic_pulse_r1_affix.tres",
     "Shock damage to Static target restores 1 mana. Max 2/turn.",
     "[element:shock] damage to [status:static] target restores 1 mana. Max 2/turn."),
    ("resources/affixes/classes/mage/storm/galvanic_pulse/galvanic_pulse_r2_affix.tres",
     "Shock damage to Static target restores 2 mana. Max 2/turn.",
     "[element:shock] damage to [status:static] target restores 2 mana. Max 2/turn."),
    ("resources/affixes/classes/mage/storm/charged_cascade/charged_cascade_r1_affix.tres",
     "Chain bounces deal +3 bonus damage per Static stack on bounce target.",
     "Chain bounces deal +3 bonus damage per [status:static] stack on bounce target."),

    # ==== CLASS AFFIXES - FROST ====
    ("resources/affixes/classes/mage/frost/glaciate/glaciate_element_unlock.tres",
     "Unlocks Ice mana element.",
     "Unlocks [element:ice] mana element."),
    ("resources/affixes/classes/mage/frost/glaciate/glaciate_ca_affix.tres",
     "Chromatic Bolt applies 2 Chill on hit (requires ice die).",
     "Chromatic Bolt applies 2 [status:chill] on hit (requires [element:ice] die)."),
    ("resources/affixes/classes/mage/frost/creeping_frost/creeping_frost_r1_affix.tres",
     "Ice dice apply 1 Chill on use.",
     "[element:ice] dice apply 1 [status:chill] on use."),
    ("resources/affixes/classes/mage/frost/creeping_frost/creeping_frost_r2_affix.tres",
     "Ice dice apply 2 Chill on use.",
     "[element:ice] dice apply 2 [status:chill] on use."),
    ("resources/affixes/classes/mage/frost/creeping_frost/creeping_frost_r3_affix.tres",
     "Ice dice apply 3 Chill on use.",
     "[element:ice] dice apply 3 [status:chill] on use."),
    ("resources/affixes/classes/mage/frost/rime_dice/rime_dice_last_r1_affix.tres",
     "Ice die in last position: apply 2 Chill.",
     "[element:ice] die in last position: apply 2 [status:chill]."),
    ("resources/affixes/classes/mage/frost/rime_dice/rime_dice_last_r2_affix.tres",
     "Ice die in last position: apply 3 Chill.",
     "[element:ice] die in last position: apply 3 [status:chill]."),
    ("resources/affixes/classes/mage/frost/brittle/brittle_r1_affix.tres",
     "Ice die: +1 damage per 4 Chill stacks on target.",
     "[element:ice] die: +1 damage per 4 [status:chill] stacks on target."),
    ("resources/affixes/classes/mage/frost/brittle/brittle_r2_affix.tres",
     "Ice die: +2 damage per 4 Chill stacks on target.",
     "[element:ice] die: +2 damage per 4 [status:chill] stacks on target."),
    ("resources/affixes/classes/mage/frost/brittle/brittle_r3_affix.tres",
     "Ice die: +3 damage per 4 Chill stacks on target.",
     "[element:ice] die: +3 damage per 4 [status:chill] stacks on target."),
    ("resources/affixes/classes/mage/frost/hoarfrost/hoarfrost_r1_affix.tres",
     "End of turn: 1 Chill per unused die.",
     "End of turn: 1 [status:chill] per unused die."),
    ("resources/affixes/classes/mage/frost/hoarfrost/hoarfrost_r2_affix.tres",
     "End of turn: 2 Chill per unused die.",
     "End of turn: 2 [status:chill] per unused die."),
    ("resources/affixes/classes/mage/frost/frostbite/frostbite_r1_affix.tres",
     "Chill Freeze threshold reduced by 2.",
     "[status:chill] [status:freeze|Freeze] threshold reduced by 2."),
    ("resources/affixes/classes/mage/frost/frostbite/frostbite_r2_affix.tres",
     "Chill Freeze threshold reduced by 4.",
     "[status:chill] [status:freeze|Freeze] threshold reduced by 4."),
    ("resources/affixes/classes/mage/frost/black_ice/black_ice_dmg_r1_affix.tres",
     "At 8+ Chill: +3 bonus damage.",
     "At 8+ [status:chill]: +3 bonus damage."),
    ("resources/affixes/classes/mage/frost/black_ice/black_ice_dmg_r2_affix.tres",
     "At 8+ Chill: +5 bonus damage.",
     "At 8+ [status:chill]: +5 bonus damage."),
    ("resources/affixes/classes/mage/frost/spreading_cold/spreading_cold_r1_affix.tres",
     "Ice die splashes 30% of Chill applied to all other enemies.",
     "[element:ice] die splashes 30% of [status:chill] applied to all other enemies."),
    ("resources/affixes/classes/mage/frost/spreading_cold/spreading_cold_r2_affix.tres",
     "Ice die splashes 50% of Chill applied to all other enemies.",
     "[element:ice] die splashes 50% of [status:chill] applied to all other enemies."),
    ("resources/affixes/classes/mage/frost/frozen_conduit/frozen_conduit_r1_affix.tres",
     "Ice die value +1 per 3 Chill stacks on target.",
     "[element:ice] die value +1 per 3 [status:chill] stacks on target."),
    ("resources/affixes/classes/mage/frost/avalanche/avalanche_r1_affix.tres",
     "When Freeze triggers: apply 3 Chill to all other enemies.",
     "When [status:freeze] triggers: apply 3 [status:chill] to all other enemies."),
    ("resources/affixes/classes/mage/frost/avalanche/avalanche_r2_affix.tres",
     "When Freeze triggers: apply 5 Chill to all other enemies.",
     "When [status:freeze] triggers: apply 5 [status:chill] to all other enemies."),
    ("resources/affixes/classes/mage/frost/entropy/entropy_r1_affix.tres",
     "Start of turn: if any enemy has 10+ Chill, restore 2 mana and next ice die +3.",
     "Start of turn: if any enemy has 10+ [status:chill], restore 2 mana and next [element:ice] die +3."),
    ("resources/affixes/classes/mage/frost/rimestorm/rimestorm_r1_affix.tres",
     "Ice die chains to 1 extra enemy (60% damage, 2 Chill).",
     "[element:ice] die chains to 1 extra enemy (60% damage, 2 [status:chill])."),
    ("resources/affixes/classes/mage/frost/crystallize/crystallize_r1_affix.tres",
     "Damage to Frozen target: gain 4 Barrier, target loses 2 ice resistance permanently.",
     "Damage to [status:freeze|Frozen] target: gain 4 Barrier, target loses 2 [element:ice] resistance permanently."),
    ("resources/affixes/classes/mage/frost/entropic_cascade/entropic_cascade_spread_affix.tres",
     "When Freeze triggers: all Chill on all enemies +3.",
     "When [status:freeze] triggers: all [status:chill] on all enemies +3."),

    # ==== REGION 1 AFFIXES - OFFENSE ====
    ("resources/affixes/region_1/offense/tier_2/apply_bleed_on_hit.tres",
     "{proc_chance}% chance to apply Bleed on hit",
     "{proc_chance}% chance to apply [status:bleed] on hit"),
    ("resources/affixes/region_1/offense/tier_2/apply_burn_on_hit.tres",
     "{proc_chance}% chance to apply Burn on hit",
     "{proc_chance}% chance to apply [status:burn] on hit"),
    ("resources/affixes/region_1/offense/tier_2/apply_chill_on_hit.tres",
     "{proc_chance}% chance to apply Chill on hit",
     "{proc_chance}% chance to apply [status:chill] on hit"),
    ("resources/affixes/region_1/offense/tier_2/apply_poison_on_hit.tres",
     "{proc_chance}% chance to apply Poison on hit",
     "{proc_chance}% chance to apply [status:poison] on hit"),
    ("resources/affixes/region_1/offense/tier_2/fire_damage_bonus.tres",
     "+{value} Fire damage",
     "+{value} [element:fire] damage"),
    ("resources/affixes/region_1/offense/tier_2/ice_damage_bonus.tres",
     "+{value} Ice damage",
     "+{value} [element:ice] damage"),
    ("resources/affixes/region_1/offense/tier_2/poison_damage_bonus.tres",
     "+{value} Poison damage",
     "+{value} [element:poison] damage"),
    ("resources/affixes/region_1/offense/tier_2/shadow_damage_bonus.tres",
     "+{value} Shadow damage",
     "+{value} [element:shadow] damage"),
    ("resources/affixes/region_1/offense/tier_2/shock_damage_bonus.tres",
     "+{value} Shock damage",
     "+{value} [element:shock] damage"),
    ("resources/affixes/region_1/offense/tier_3/apply_corrode_on_hit.tres",
     "{proc_chance}% chance to apply Corrode on hit",
     "{proc_chance}% chance to apply [status:corrode] on hit"),
    ("resources/affixes/region_1/offense/tier_3/apply_enfeeble_on_hit.tres",
     "{proc_chance}% chance to apply Enfeeble on hit",
     "{proc_chance}% chance to apply [status:enfeeble] on hit"),
    ("resources/affixes/region_1/offense/tier_3/apply_expose_on_hit.tres",
     "{proc_chance}% chance to apply Expose on hit",
     "{proc_chance}% chance to apply [status:expose] on hit"),
    ("resources/affixes/region_1/offense/tier_3/apply_shadow_on_hit.tres",
     "{proc_chance}% chance to apply Shadow on hit",
     "{proc_chance}% chance to apply [status:shadow] on hit"),
    ("resources/affixes/region_1/offense/tier_3/apply_slowed_on_hit.tres",
     "{proc_chance}% chance to apply Slowed on hit",
     "{proc_chance}% chance to apply [status:slowed] on hit"),
    ("resources/affixes/region_1/offense/tier_1/blunt_damage_bonus.tres",
     "+{value} Blunt damage",
     "+{value} [element:blunt] damage"),
    ("resources/affixes/region_1/offense/tier_1/piercing_damage_bonus.tres",
     "+{value} Piercing damage",
     "+{value} [element:piercing] damage"),
    ("resources/affixes/region_1/offense/tier_1/slashing_damage_bonus.tres",
     "+{value} Slashing damage",
     "+{value} [element:slashing] damage"),

    # ==== REGION 1 AFFIXES - DEFENSE thorns ====
    ("resources/affixes/region_1/defense/tier_3/thorns_chill.tres",
     "{proc_chance}% chance to Chill attacker when hit",
     "{proc_chance}% chance to [status:chill|Chill] attacker when hit"),
    ("resources/affixes/region_1/defense/tier_3/thorns_corrode.tres",
     "{proc_chance}% chance to Corrode attacker when hit",
     "{proc_chance}% chance to [status:corrode|Corrode] attacker when hit"),
    ("resources/affixes/region_1/defense/tier_3/thorns_enfeeble.tres",
     "{proc_chance}% chance to Enfeeble attacker when hit",
     "{proc_chance}% chance to [status:enfeeble|Enfeeble] attacker when hit"),
    ("resources/affixes/region_1/defense/tier_3/thorns_slowed.tres",
     "{proc_chance}% chance to Slow attacker when hit",
     "{proc_chance}% chance to [status:slowed|Slow] attacker when hit"),

    # ==== BASE AFFIXES - OFFENSE ====
    ("resources/affixes/base/offense/tier_2/apply_burn_on_hit.tres",
     "{proc_chance}% chance to Burn on hit",
     "{proc_chance}% chance to [status:burn|Burn] on hit"),
    ("resources/affixes/base/offense/tier_2/apply_bleed_on_hit.tres",
     "{proc_chance}% chance to Bleed on hit",
     "{proc_chance}% chance to [status:bleed|Bleed] on hit"),
    ("resources/affixes/base/offense/tier_2/apply_chill_on_hit.tres",
     "{proc_chance}% chance to Chill on hit",
     "{proc_chance}% chance to [status:chill|Chill] on hit"),
    ("resources/affixes/base/offense/tier_2/apply_poison_on_hit.tres",
     "{proc_chance}% chance to Poison on hit",
     "{proc_chance}% chance to [status:poison|Poison] on hit"),
    ("resources/affixes/base/offense/tier_2/fire_damage_bonus.tres",
     "+N Fire damage",
     "+N [element:fire] damage"),
    ("resources/affixes/base/offense/tier_2/ice_damage_bonus.tres",
     "+N Ice damage",
     "+N [element:ice] damage"),
    ("resources/affixes/base/offense/tier_2/shock_damage_bonus.tres",
     "+N Shock damage",
     "+N [element:shock] damage"),
    ("resources/affixes/base/offense/tier_2/poison_damage_bonus.tres",
     "+N Poison damage",
     "+N [element:poison] damage"),
    ("resources/affixes/base/offense/tier_2/shadow_damage_bonus.tres",
     "+N Shadow damage",
     "+N [element:shadow] damage"),
    ("resources/affixes/base/offense/tier_3/apply_corrode_on_hit.tres",
     "{proc_chance}% chance to Corrode on hit",
     "{proc_chance}% chance to [status:corrode|Corrode] on hit"),
    ("resources/affixes/base/offense/tier_3/apply_expose_on_hit.tres",
     "{proc_chance}% chance to Expose on hit",
     "{proc_chance}% chance to [status:expose|Expose] on hit"),
    ("resources/affixes/base/offense/tier_3/apply_shadow_on_hit.tres",
     "{proc_chance}% chance to Shadow on hit",
     "{proc_chance}% chance to [status:shadow|Shadow] on hit"),
    ("resources/affixes/base/offense/tier_3/apply_slowed_on_hit.tres",
     "{proc_chance}% chance to Slow on hit",
     "{proc_chance}% chance to [status:slowed|Slow] on hit"),
    ("resources/affixes/base/offense/tier_1/blunt_damage_bonus.tres",
     "+N Blunt damage",
     "+N [element:blunt] damage"),
    ("resources/affixes/base/offense/tier_1/piercing_damage_bonus.tres",
     "+N Piercing damage",
     "+N [element:piercing] damage"),
    ("resources/affixes/base/offense/tier_1/slashing_damage_bonus.tres",
     "+N Slashing damage",
     "+N [element:slashing] damage"),

    # ==== BASE AFFIXES - DEFENSE thorns ====
    ("resources/affixes/base/defense/tier_3/thorns_chill.tres",
     "{proc_chance}% chance to Chill attacker when hit",
     "{proc_chance}% chance to [status:chill|Chill] attacker when hit"),
    ("resources/affixes/base/defense/tier_3/thorns_corrode.tres",
     "{proc_chance}% chance to Corrode attacker when hit",
     "{proc_chance}% chance to [status:corrode|Corrode] attacker when hit"),
    ("resources/affixes/base/defense/tier_3/thorns_slowed.tres",
     "{proc_chance}% chance to Slow attacker when hit",
     "{proc_chance}% chance to [status:slowed|Slow] attacker when hit"),
    ("resources/affixes/base/defense/tier_3/thorns_enfeeble.tres",
     "{proc_chance}% chance to Enfeeble attacker when hit",
     "{proc_chance}% chance to [status:enfeeble|Enfeeble] attacker when hit"),

    # ==== WEAPON/GLOVE/OLD AFFIXES ====
    ("resources/affixes/weapon/legendary/flareburst_affix.tres",
     "20% chance to deal +10 Fire damage.",
     "20% chance to deal +10 [element:fire] damage."),
    ("resources/affixes/gloves/second/fire_fist_affix.tres",
     "Adds +5 Fire damage to each attack.",
     "Adds +5 [element:fire] damage to each attack."),

    # ==== NAVY DICE AFFIXES ====
    ("resources/dice_affixes/navy/da_breach_protocol.tres",
     "Last die used applies Corrode to the enemy.",
     "Last die used applies [status:corrode] to the enemy."),
    ("resources/dice_affixes/navy/da_serrated_edge.tres",
     "When die value is 3 or below, apply Bleed to enemy.",
     "When die value is 3 or below, apply [status:bleed] to enemy."),
    ("resources/dice_affixes/navy/da_marked_target.tres",
     "Last die used applies Expose to enemy.",
     "Last die used applies [status:expose] to enemy."),
    ("resources/dice_affixes/navy/da_disruptor_pulse.tres",
     "First die used applies Corrode if target already has Corrode.",
     "First die used applies [status:corrode] if target already has [status:corrode]."),
    ("resources/dice_affixes/navy/da_charged_air.tres",
     "On max roll, gain Warded.",
     "On max roll, gain [status:warded]."),
    ("resources/dice_affixes/navy/da_lingering_flame.tres",
     "Last die used applies Burn to enemy.",
     "Last die used applies [status:burn] to enemy."),
    ("resources/dice_affixes/navy/da_shield_brace.tres",
     "First die rolled grants Fortified.",
     "First die rolled grants [status:fortified]."),
    ("resources/dice_affixes/navy/da_passive_ward.tres",
     "First die rolled grants Warded.",
     "First die rolled grants [status:warded]."),
    ("resources/dice_affixes/navy/da_tidal_surge.tres",
     "On max roll, apply Chill to enemy.",
     "On max roll, apply [status:chill] to enemy."),
    ("resources/dice_affixes/navy/da_blinding_flash.tres",
     "On max roll, first die applies Enfeeble to enemy.",
     "On max roll, first die applies [status:enfeeble] to enemy."),

    # ==== FLAME DICE AFFIXES ====
    ("resources/dice_affixes/mage/flame/da_fuel_the_fire_r1.tres",
     "+2 damage vs burning target.",
     "+2 damage vs [status:burn|burning] target."),
    ("resources/dice_affixes/mage/flame/da_fuel_the_fire_r2.tres",
     "+4 damage vs burning target.",
     "+4 damage vs [status:burn|burning] target."),
    ("resources/dice_affixes/mage/flame/da_fuel_the_fire_r3.tres",
     "+6 damage vs burning target.",
     "+6 damage vs [status:burn|burning] target."),
    ("resources/dice_affixes/mage/flame/da_flashfire_r1.tres",
     "Max roll: apply 2 Burn to random enemy.",
     "Max roll: apply 2 [status:burn] to random enemy."),
    ("resources/dice_affixes/mage/flame/da_flashfire_r2.tres",
     "Max roll: apply 3 Burn to random enemy.",
     "Max roll: apply 3 [status:burn] to random enemy."),
    ("resources/dice_affixes/mage/flame/da_firestorm_r1.tres",
     "Chain to 1 enemy for 25% damage, applying 1 Burn.",
     "Chain to 1 enemy for 25% damage, applying 1 [status:burn]."),
    ("resources/dice_affixes/mage/flame/da_firestorm_r2.tres",
     "Chain to 1 enemy for 40% damage, applying 1 Burn.",
     "Chain to 1 enemy for 40% damage, applying 1 [status:burn]."),
    ("resources/dice_affixes/mage/flame/da_forge_bond_burn_first.tres",
     "FIRST fire die: apply 1 Burn.",
     "FIRST [element:fire] die: apply 1 [status:burn]."),
    ("resources/dice_affixes/mage/flame/da_forge_bond_burn_last.tres",
     "LAST fire die: apply 1 Burn.",
     "LAST [element:fire] die: apply 1 [status:burn]."),
    ("resources/dice_affixes/mage/flame/da_inferno_cascade_first.tres",
     "FIRST fire die applies 1 Burn to all enemies.",
     "FIRST [element:fire] die applies 1 [status:burn] to all enemies."),

    # ==== STORM DICE AFFIXES ====
    ("resources/dice_affixes/mage/storm/da_arc_pulse_r1.tres",
     "Apply 1 Static on use.",
     "Apply 1 [status:static] on use."),
    ("resources/dice_affixes/mage/storm/da_arc_pulse_r2.tres",
     "Apply 2 Static on use.",
     "Apply 2 [status:static] on use."),
    ("resources/dice_affixes/mage/storm/da_arc_pulse_r3.tres",
     "Apply 3 Static on use.",
     "Apply 3 [status:static] on use."),
    ("resources/dice_affixes/mage/storm/da_ionize_r1.tres",
     "Pulling shock die applies 1 Static.",
     "Pulling [element:shock] die applies 1 [status:static]."),
    ("resources/dice_affixes/mage/storm/da_ionize_r2.tres",
     "Pulling shock die applies 2 Static.",
     "Pulling [element:shock] die applies 2 [status:static]."),
    ("resources/dice_affixes/mage/storm/da_ionize_r3.tres",
     "Pulling shock die applies 3 Static.",
     "Pulling [element:shock] die applies 3 [status:static]."),
    ("resources/dice_affixes/mage/storm/da_live_wire_r1.tres",
     "+1 bonus Static if target has Static.",
     "+1 bonus [status:static] if target has [status:static]."),
    ("resources/dice_affixes/mage/storm/da_live_wire_r2.tres",
     "+2 bonus Static if target has Static.",
     "+2 bonus [status:static] if target has [status:static]."),
    ("resources/dice_affixes/mage/storm/da_arc_conduit_r1.tres",
     "Chains hit +1 target. Bounces apply 1 Static.",
     "Chains hit +1 target. Bounces apply 1 [status:static]."),
    ("resources/dice_affixes/mage/storm/da_arc_conduit_r2.tres",
     "Chains hit +1 target. Bounces apply 2 Static.",
     "Chains hit +1 target. Bounces apply 2 [status:static]."),
    ("resources/dice_affixes/mage/storm/da_voltaic_surge_r1.tres",
     "+1 damage per Static stack.",
     "+1 damage per [status:static] stack."),
    ("resources/dice_affixes/mage/storm/da_voltaic_surge_r2.tres",
     "+2 damage per Static stack.",
     "+2 damage per [status:static] stack."),
    ("resources/dice_affixes/mage/storm/da_voltaic_surge_r3.tres",
     "+3 damage per Static stack.",
     "+3 damage per [status:static] stack."),
    ("resources/dice_affixes/mage/storm/da_charged_cascade.tres",
     "Chain bounces deal +3 damage per Static stack on bounce target.",
     "Chain bounces deal +3 damage per [status:static] stack on bounce target."),
    ("resources/dice_affixes/mage/storm/da_eye_first_strike.tres",
     "First-position shock die applies 2 Static to all enemies.",
     "First-position [element:shock] die applies 2 [status:static] to all enemies."),

    # ==== FROST DICE AFFIXES ====
    ("resources/dice_affixes/mage/frost/da_creeping_frost_r1.tres",
     "Apply 1 Chill on use.",
     "Apply 1 [status:chill] on use."),
    ("resources/dice_affixes/mage/frost/da_creeping_frost_r2.tres",
     "Apply 2 Chill on use.",
     "Apply 2 [status:chill] on use."),
    ("resources/dice_affixes/mage/frost/da_creeping_frost_r3.tres",
     "Apply 3 Chill on use.",
     "Apply 3 [status:chill] on use."),
    ("resources/dice_affixes/mage/frost/da_rime_last_r1.tres",
     "Last-position ice die applies 2 Chill.",
     "Last-position [element:ice] die applies 2 [status:chill]."),
    ("resources/dice_affixes/mage/frost/da_rime_last_r2.tres",
     "Last-position ice die applies 3 Chill.",
     "Last-position [element:ice] die applies 3 [status:chill]."),
    ("resources/dice_affixes/mage/frost/da_brittle_r1.tres",
     "+1 damage per 4 Chill on target.",
     "+1 damage per 4 [status:chill] on target."),
    ("resources/dice_affixes/mage/frost/da_brittle_r2.tres",
     "+2 damage per 4 Chill on target.",
     "+2 damage per 4 [status:chill] on target."),
    ("resources/dice_affixes/mage/frost/da_brittle_r3.tres",
     "+3 damage per 4 Chill on target.",
     "+3 damage per 4 [status:chill] on target."),
    ("resources/dice_affixes/mage/frost/da_black_ice_dmg_r1.tres",
     "+3 flat damage at 8+ Chill.",
     "+3 flat damage at 8+ [status:chill]."),
    ("resources/dice_affixes/mage/frost/da_black_ice_dmg_r2.tres",
     "+5 flat damage at 8+ Chill.",
     "+5 flat damage at 8+ [status:chill]."),
    ("resources/dice_affixes/mage/frost/da_spreading_cold_r1.tres",
     "Splash 30% of applied Chill to all other enemies.",
     "Splash 30% of applied [status:chill] to all other enemies."),
    ("resources/dice_affixes/mage/frost/da_spreading_cold_r2.tres",
     "Splash 50% of applied Chill to all other enemies.",
     "Splash 50% of applied [status:chill] to all other enemies."),
    ("resources/dice_affixes/mage/frost/da_frozen_conduit.tres",
     "Ice die +1 value per 3 Chill stacks on target.",
     "[element:ice] die +1 value per 3 [status:chill] stacks on target."),
    ("resources/dice_affixes/mage/frost/da_rimestorm.tres",
     "Ice die chains to 1 additional enemy for 60% damage, applying 2 Chill.",
     "[element:ice] die chains to 1 additional enemy for 60% damage, applying 2 [status:chill]."),

    # ==== ROLLABLE COMBAT DICE AFFIXES ====
    ("resources/dice_affixes/rollable/combat/tier_1/add_fire_damage_flat.tres",
     "+N flat fire damage on use",
     "+N flat [element:fire] damage on use"),
    ("resources/dice_affixes/rollable/combat/tier_1/add_ice_damage_flat.tres",
     "+N flat ice damage on use",
     "+N flat [element:ice] damage on use"),
    ("resources/dice_affixes/rollable/combat/tier_1/add_shock_damage_flat.tres",
     "+N flat shock damage on use",
     "+N flat [element:shock] damage on use"),
    ("resources/dice_affixes/rollable/combat/tier_1/add_poison_damage_flat.tres",
     "+N flat poison damage on use",
     "+N flat [element:poison] damage on use"),
    ("resources/dice_affixes/rollable/combat/tier_2/grant_burn_status.tres",
     "Apply Burn on use",
     "Apply [status:burn] on use"),
    ("resources/dice_affixes/rollable/combat/tier_2/grant_chill_status.tres",
     "Apply Chill on use",
     "Apply [status:chill] on use"),
    ("resources/dice_affixes/rollable/combat/tier_2/grant_shock_status.tres",
     "Apply Shock on use",
     "Apply [status:static|Shock] on use"),
]

def edit_file(rel_path, old_val, new_val):
    path = os.path.join(BASE, rel_path).replace("\\", "/")
    old_str = f'description = "{old_val}"'
    new_str = f'description = "{new_val}"'
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        if old_str in content:
            new_content = content.replace(old_str, new_str, 1)
            with open(path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"OK: {rel_path}")
        else:
            print(f"MISS: {old_val[:60]!r} in {rel_path}")
    except Exception as e:
        print(f"ERR {rel_path}: {e}")

for rel, old, new in affix_edits:
    edit_file(rel, old, new)

print("\nAll affix/dice_affix edits done")
